name: Build and Push
on:
  push:
    branches:
      - v[0-9]+.[0-9]+


jobs:
  success_build:
    
    if: (!contains(github.event.head_commit.message, '#NORUN'))
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
      id-token: write
    steps:
    # Check out code
    - name: Check out the code
      uses: actions/checkout@v3

    # Install Cosign
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0
      with:
        cosign-release: 'v2.2.4'

    # Scan code for vulnerabilities with Trivy
    - name: Scan for Vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        severity: 'CRITICAL'

    # Send Slack Notification
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2

      env:
        SLACK_TITLE: "Image build and signed"
        SLACK_MESSAGE: |
          Name: Tint Wai Yan Min
          Matriculation: A0290835X
          Email: e1327866@u.nus.edu
          GitHub: https://github.com/tintwym/CI-CD_Workshop
        SLACK_WEBHOOK: ${{ secrets.SECRET_WEBHOOK_URL }}

      

      